site_name: Serra Vine
site_url: https://vine.serraict.com
theme:
  name: material
  language: nl
  logo: "img/logo_serra.png"
  palette:
    scheme: default
    primary: custom
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - "Voor Kwekers": voor-kwekers.md
  - "Voor Ontwikkelaars": voor-ontwikkelaars.md
  - "Over Serra":
      - "Contact": contact.md
      - "Producten en Diensten": producten-en-diensten.md
